### ISSUE TITLE
How to disable the bot from telling me that it posted a message from Discord to Rust Team Chat?

### ISSUE THREAD

**Issue by ghostsquad** [javajuice1337/RustPlusBot#3]
![image](https://github.com/javajuice1337/RustPlusBot/assets/903488/2aa6c0a8-cbf3-42ed-8d41-1c3cadeb5a60)

this becomes _very_ spammy. The only way I've found I can prevent the spam is unchecking this box:
![image](https://github.com/javajuice1337/RustPlusBot/assets/903488/e0a3de38-b843-4be3-9137-b37ebe94d676)

But I _do_ want messages to be sent to Rust team chat.

**Comment by javajuice1337** [comment]
Hello, this is by design since the message you are seeing in Discord was sent from team chat.

Also, this is not the correct place for support. For future support, please post here: https://discord.rustrician.io/
